# Generated by Django 5.0.6 on 2024-07-26 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anemia_estimation', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
